### ISSUE TITLE
Assignments and grading 

### ISSUE THREAD

**Issue by robweir** [j4502/stewart#1]

**Comment by emilypstewart** [comment]
Shoot. Just saw this. Face palm. I went through and broke down the grading. It looks like we were on the same page though:

https://github.com/emilypstewart/j4502/wiki/Syllabus#milestones-and-due-dates

Does this work? Does it seem to heavily weighted?

**Comment by robweir** [comment]
That seems completely fine. I don't want the final to be more than 40% of the grade, so 33% sounds about right.
