### ISSUE TITLE
Blogging

### ISSUE THREAD

**Issue by robweir** [j4502/stewart#2]

**Comment by emilypstewart** [comment]
Oh, hmm, I'm on the fence about this. I like the idea of it, but I remember how much I struggled with it as a student.

I was thinking 2 extra credit assignments to write a Medium post about [TBD]? Thoughts? 
And then having design critiques in class / slack?

**Comment by robweir** [comment]
Design critiques in class is something I usually just sprinkle in. That's where the participation grade comes in, when we threaten them to speak :smiley: 

I think that maybe two Medium assignments would be a good compromise, so that they get used to a public (rest of world) critique. 

The only question about having design critiques in Slack is whether those are archivable? In case someone would contest a grade, I like having a paper trail.

**Comment by emilypstewart** [comment]
Good point. We'll need to make sure we export all transcripts at the end of the semester (just in case). I'm gonna move this to Slack DM—have some more thoughts.
